CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  email VARCHAR(256) NOT NULL,
  password_hash VARCHAR(256) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY fk_users_id(user_id) REFERENCES users(id)
);

ALTER TABLE accounts ADD UNIQUE uidx_accounts_01 (email);
ALTER TABLE accounts ADD INDEX idx_accounts_01 (email);

